name: Claustrophobia
version: '${project.version}'
main: me.pm7.claustrophobia.Claustrophobia
api-version: 1.21
authors: [ _Pm7 ]
description: A cooped up minigame built to ruin friendships
commands:
  startgame:
    description: Starts the game at the command sender's location
  revive:
    description: fkjd
  votemenu:
    description: opens the vote menu