name: Claustrophobia
version: '1.0'
main: me.pm7.claustrophobia.Claustrophobia
api-version: 1.21
authors: [ _Pm7 ]
description: A cooped up minigame built to ruin friendships
commands:
  startgame:
    description: stort
  revive:
    description: fkjd